### PR TITLE
Arcify the class

### PR DESCRIPTION
**Pull request by Abizern**
- Surrounded the memory management calls with the appropriate guards
- Replaced a non-existent assertion macro with an thrown exception
- Consistent naming.

### CODE REVIEW

**Comment by Abizern** [comment]
Reverted the bad commit.

**Comment by mikeabdullah** [comment]
Cheers. I'm making some further changes which you could pull back into your branch if that's OK.

**Comment by Abizern** [comment]
Okay.

## 

Abizer Nasir

**Comment by Abizern** [comment]
I've updated the my fork and the pull request.

**Comment by mikeabdullah** [comment]
More changes pushed; that's my lot

**Comment by Abizern** [comment]
I've got one more to push in a few minutes

## 

Abizer Nasir

**Comment by Abizern** [comment]
I've dropped into CF land to replace the deprecated call and the guards. Unfamiliar territory - so I'd appreciate a second opinion.

Also - I think you may have made a typo with the Inception call - feel free to correct my correction if that is not the case.

**Comment by mikeabdullah** [comment]
Oh, and what's the typo? Feel I'm missing something.

**Pull request merged**
